version: '3.8'

services:
  finder:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: finder-app

# Docker ile çalıştırma:
# docker-compose up -d